export const ROUTES = {
  LANDING: 'landing',
  LOGIN: 'login',
  CADASTRO: 'cadastro',
  RECUPERAR_SENHA: 'recuperar-senha',
  DASHBOARD: 'dashboard',
  PERFIS: 'perfis',
  PERFIS_VAZIO: 'perfis-vazio',
  CADASTRO_STEP_1: 'cadastro-step-1',
  CADASTRO_STEP_2: 'cadastro-step-2',
  CADASTRO_STEP_3: 'cadastro-step-3',
  CADASTRO_STEP_4: 'cadastro-step-4',
  CADASTRO_STEP_5: 'cadastro-step-5',
  LISTA_CUIDADORES: 'lista-cuidadores',
  PERFIL_CUIDADOR: 'perfil-cuidador',
  CONFIRMACAO_SOLICITACAO: 'confirmacao-solicitacao',
  MINHAS_SOLICITACOES: 'minhas-solicitacoes',
  AGENDAMENTOS: 'agendamentos',
};
